defaults:
  - model: pspnet
  - dataset: pet
  - _self_             

hydra:
  run:
    dir: ./logs/${dataset.dataset_name}/${model.model_name}/${hydra:job.name}/${now:%Y-%m-%d}/${now:%H-%M-%S}

job_name: ${hydra:job.name}

trainer:
  max_epochs: 100
  devices: [0,1]
  accelerator: "gpu"
  check_val_every_n_epoch: 1
  log_every_n_steps: 10
  precision: "bf16-mixed"


optimizer:
  lr: 1e-2
  momentum: 0.9
  weight_decay: 1e-4

scheduler:
  power: 0.9

visualization:
  num_samples: 2

manual_optimization: false
ckpt_path: "./checkpoint_demo/demo-epoch=06-val_loss=0.18.ckpt"